name: calendar_of_life
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  firebase_core: ^3.8.1
  google_gemini: ^0.1.2
  path_provider: ^2.1.5
  google_cloud: ^0.2.0
  googleapis: ^13.2.0
  google_sign_in: ^6.2.2
  syncfusion_flutter_calendar: ^28.1.33
  intl: ^0.19.0
  googleapis_auth: ^1.6.0
  json_serializable: ^6.9.0
  provider: ^6.1.2
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_database: ^11.3.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
