// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Pvr12gUqybk5FZtdKBOw4Cl6ZCgDmx4',
    appId: '1:1001415118047:web:752ef8cf93cd7e52782d6a',
    messagingSenderId: '1001415118047',
    projectId: 'calendaroflife-dcea0',
    authDomain: 'calendaroflife-dcea0.firebaseapp.com',
    storageBucket: 'calendaroflife-dcea0.firebasestorage.app',
    measurementId: 'G-DF0YZ1VL0H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCadm_yplmKNC8TI5nigBfQGaIgd4rK0Rc',
    appId: '1:1001415118047:android:6e6d2d01be6fca20782d6a',
    messagingSenderId: '1001415118047',
    projectId: 'calendaroflife-dcea0',
    storageBucket: 'calendaroflife-dcea0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzUM6kh3x54xVGpx4TAzenUr3zgwYsWxs',
    appId: '1:1001415118047:ios:df0473e3d38f4670782d6a',
    messagingSenderId: '1001415118047',
    projectId: 'calendaroflife-dcea0',
    storageBucket: 'calendaroflife-dcea0.firebasestorage.app',
    iosBundleId: 'com.example.calendarOfLife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzUM6kh3x54xVGpx4TAzenUr3zgwYsWxs',
    appId: '1:1001415118047:ios:df0473e3d38f4670782d6a',
    messagingSenderId: '1001415118047',
    projectId: 'calendaroflife-dcea0',
    storageBucket: 'calendaroflife-dcea0.firebasestorage.app',
    iosBundleId: 'com.example.calendarOfLife',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB4Pvr12gUqybk5FZtdKBOw4Cl6ZCgDmx4',
    appId: '1:1001415118047:web:fe2a19b786877764782d6a',
    messagingSenderId: '1001415118047',
    projectId: 'calendaroflife-dcea0',
    authDomain: 'calendaroflife-dcea0.firebaseapp.com',
    storageBucket: 'calendaroflife-dcea0.firebasestorage.app',
    measurementId: 'G-C12FH3EFKV',
  );
}
